[variables]
NODE_VERSION = "22"
NPM_CONFIG_PRODUCTION = "false"
PORT = "8080"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmd = "NODE_ENV=production node dist-server/server.cjs"

[start]
cmd = "NODE_ENV=production node dist-server/server.cjs"
